src/Entity/File.php
<?php

namespace App\Entity;

use App\Repository\FileRepository;
use App\Service\UploaderHelper;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=FileRepository::class)
 */
class File
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function getImagePath(): string
    {
        return UploaderHelper::MISSION_IMAGE.'/'.$this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }
}

templates/macros/_macro_upload.html.twig
{% macro image(file, file_object) %}
    <div class="form-error">
        {{ form_errors(file) }}
    </div>
    <div class="js-macro-upload-image">
        <div class="js-parent-element">
            {% set uploaded_file = false %}
            {% if file_object and file_object.name %}
                {% set uploaded_file = true %}

                <div class="col">
                    <div class="cs-upload-image-block">
                        Vous-avez déjà uploader un document pour le
                        <a target="_blank" href="{{ path('front_mission_consulter', {id: file_object.id}) }}">consulter</a>
                        <p>
                            Si vous souhaiter le mettre à jour cliquer
                            <span class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                       <a href="#" class="js-show-element" data-class-parent=".js-toggle-show">ici</a>
                                               </span>
                        </p>
                    </div>
                </div>

            {% endif %}
        </div>

        <div class="js-toggle-show {{ uploaded_file ? 'd-none' }}">
            {{ form_widget(file) }}
        </div>
    </div>
{% endmacro %}

{% macro show_image(file_object) %}
    <div class="js-macro-upload-image">
        <div class="js-parent-element">
            {% set uploaded_file = false %}
            {% if file_object and file_object.name %}
                {% set uploaded_file = true %}

                <div class="col-12 text-center">
                    <div class="cs-upload-image-block">
                        <a target="_blank" href="{{ path('front_mission_consulter', {id: file_object.id}) }}">Voir le document</a>
                    </div>
                </div>

            {% endif %}
        </div>
    </div>
{% endmacro %}

{% macro only_bouton(file, file_object) %}
    <div class="form-error">
        {{ form_errors(file) }}
    </div>
    <div class="js-parent-element">
        {% set uploaded_file = false %}
        {% if file_object and file_object.name %}
            {% set uploaded_file = true %}

            <div class="col mt-2">
                <a target="_blank" href="{{ path('front_mission_consulter', {id: file_object.id}) }}">
                    <span class="fa fa-eye text-primary" title="consulter le fichier"></span>
                </a>
                &nbsp;
                &nbsp;
                <a href="#" class="js-show-element" data-class-parent=".js-toggle-show">
                    <span class="fa fa-pencil-alt text-info" title="Modifier le fichier"></span>
                </a>
            </div>

        {% endif %}
    </div>

    <div class="js-toggle-show {{ uploaded_file ? 'd-none' }}">
        {{ form_row(file) }}
    </div>
{% endmacro %}

{% macro printExperience(experience, with_div) %}

    {% from 'macros/_macro_upload.html.twig' import only_bouton as upload %}

    {% if with_div|default %}
        <div class="row js-genus-scientist-item">
    {% endif %}

    <div class="col-12 col-sm-3 my-1">
        {{ form_errors(experience.label) }}
        {{ form_widget(experience.label) }}
    </div>
    {% if 'file' in experience|keys %}

        <div class="col-12 col-sm-7 my-1 js-macro-upload-image">

           <div class="d-flex">
               {% if experience.vars.value.file|default
               %}
                   <div class="px-2">
                       <img src="{{ experience.vars.value.file.imagePath|imagine_filter('thumbnail_small') }}" class="shop-image img-fluid rounded-circle" alt="Image non disponible">
                   </div>
               {% endif %}

               {{ form_row(experience.file, {attr: {class: 'pt-2'}}) }}
           </div>
        </div>
    {% endif %}
    {% if with_div|default %}
        </div>
    {% endif %}
{% endmacro %}